apiVersion: v2
name: template-service
description: A Helm chart for the template service Rust application
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - template-service
  - rust
  - actix-web
maintainers:
  - name: Zirv Marketing Automation
