apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "template-service.fullname" . }}
  labels:
    {{- include "template-service.labels" . | nindent 4 }}
data:
  {{- range .Values.env }}
  {{ .name }}: {{ .value | quote }}
  {{- end }}
