apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "template-service.fullname" . }}
  labels:
    {{- include "template-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "template-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "template-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "template-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        {{- if .Values.dev.enabled }}
        image: "{{ .Values.dev.image.repository }}:{{ .Values.dev.image.tag }}"
        {{- else }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        env:
        {{- range .Values.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              {{- if .Values.database.existingSecret }}
              name: {{ .Values.database.existingSecret }}
              key: {{ .Values.database.existingSecretKey }}
              {{- else }}
              name: {{ include "template-service.fullname" . }}-db
              key: database-url
              {{- end }}
        {{- if not .Values.dev.enabled }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        {{- end }}
        resources:
          {{- if .Values.dev.enabled }}
          {{- toYaml .Values.dev.resources | nindent 12 }}
          {{- else }}
          {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
        {{- if and .Values.dev.enabled .Values.dev.sourceMount.enabled }}
        volumeMounts:
        - name: source-code
          mountPath: /usr/src/app
        {{- end }}
      {{- if and .Values.dev.enabled .Values.dev.sourceMount.enabled }}
      volumes:
      - name: source-code
        hostPath:
          path: {{ .Values.dev.sourceMount.hostPath }}
          type: Directory
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
